### ISSUE TITLE
Stripcolors doesn't

### ISSUE THREAD

**Issue by chaos95** [pyGBot/pyGBot#11]
Ok so it sort of does, but it's pretty silly. Perhaps a regex would do a better job? Or something?

**Comment by Laogeodritt** [comment]
Working on this one. I'm going to deprecate stripcolors() and create a method to strip formatting (colours, bold, etc.), since that's more useful for the chatlog pre-processing.

**Comment by chaos95** [comment]
:heart:

**Comment by Laogeodritt** [comment]
Done, fix forthcoming in my next pull request. (Just need to debug some other features I developed =P )

**Comment by Dritz** [comment]
Fixed by pull, closing.
