### ISSUE TITLE
Auth unicode passwords

### ISSUE THREAD

**Issue by Dritz** [pyGBot/pyGBot#12]
Pygbot auth fails if the user's password has unicode characters in it.

**Comment by chaos95** [comment]
Fails in what way?

**Comment by Dritz** [comment]
To the user, it's caught as a "syntax error" thanks to the latest commit. Under the hood, we're getting one of these:

exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

That was specifically when I used a single unicode snowman as a test password. I can't figure out off the top of my head what kind of encode methods will fix this up, so I sent in the issue.

**Comment by chaos95** [comment]
As per discussions in the dev channel, we have determined that this is because we are trying to `decode()` the damned thing instead of `encode()`ing it. Doi.
