### ISSUE TITLE
cprivmsg / cnotice

### ISSUE THREAD

**Issue by Dritz** [pyGBot/pyGBot#17]
Both of these are probably broken. It looks like neither sends a message, just a user and channel. Haven't had a chance to test, but there's a good probability that they don't work.

**Comment by Dritz** [comment]
Did some more research through history, these functions have been broken like that since initial commit. Great job, chaos! ;)

**Comment by chaos95** [comment]
Did even _more_ research through even _older_ history, these functions have been broken like that since before pyGBot ever existed. Great job, Paul! :P

http://pytbot.cvs.sourceforge.net/viewvc/pytbot/pytbot/pytbot?revision=1.10.2.10&view=markup

**Comment by magcius** [comment]
The pyTBot versions don't look broken to me. It just looks like the pyGBot versions are broken because they reference a "msg" variable that doesn't exist.

**Comment by chaos95** [comment]
https://github.com/pyGBot/pyGBot/commit/e57c00200b7f010c7f51cc2b38940f76025a3fbe#commitcomment-1029455

**Comment by Dritz** [comment]
My bad in that I messed up message / msg (fixed in my local code already), but either way I don't think these methods work; they never did send out the message passed in. We should just give them a complete rewrite either way, I think.

**Comment by Dritz** [comment]
Okay, magcius brought it to my attention that apparently I'm blind - was probably dismissing the second line as a log instead of a two-step send process. It'll probably be functional with the var names fixed, but I still say we should rewrite it to be more in line with the rest of the methods in core ;)

**Comment by chaos95** [comment]
This is why we need unit tests!
