### ISSUE TITLE
Roll and Math insecure

### ISSUE THREAD

**Issue by Dritz** [pyGBot/pyGBot#5]
Roll and Math currently both make use of an eval statement, which is incredibly insecure. For now they are not included in the default .ini. They should be rewritten to avoid the eval statement.

(This one's my fault. I was just learning at the time!)

**Comment by magcius** [comment]
Have something I wrote a little while ago for a similar problem: https://gist.github.com/1888430

**Comment by Dritz** [comment]
Hokay, there's a new Calc.py (based on that gist) implemented as a command in my branch. Will submit a pull request once someone else looks over it and decides if my dice rolling functionality is too hacky :p
