### ISSUE TITLE
Support multiple channels on connect

### ISSUE THREAD

**Issue by Laogeodritt** [pyGBot/pyGBot#7]
As stated in the default INI file's documentation comments, pyGBot only supports joining one channel upon connect. This could be expanded to allow joining an arbitrary number of channels automatically.

``` python
# This value controls the channel the bot will join. At the moment, it only 
# accepts one value. You can make the bot join additional channels by issuing
# the 'join' command in the channel.
```

**Comment by Dritz** [comment]
This is now implemented in my branch. I didn't find out about issue referencing until afterwards, though. Pull request coming soon.
